//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.SUS.Reports.Reports {
    
    public partial class RelatorioSus : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Api.SUS.Reports.Reports.RelatorioSus.vsrepx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.label20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label20");
            this.label16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label16");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.label13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label13");
            this.label38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label38");
            this.lblSalePriceColumnSoldItems = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblSalePriceColumnSoldItems");
            this.lblDateColumnSoldItems = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblDateColumnSoldItems");
            this.lblItemDescriptionColumnSoldItems = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblItemDescriptionColumnSoldItems");
            this.lblCodeColumnSoldItems = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblCodeColumnSoldItems");
            this.lblRoomColumnSoldItems = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("lblRoomColumnSoldItems");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.XRLabel label20;
        private DevExpress.XtraReports.UI.XRLabel label16;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRLabel label13;
        private DevExpress.XtraReports.UI.XRLabel label38;
        private DevExpress.XtraReports.UI.XRLabel lblSalePriceColumnSoldItems;
        private DevExpress.XtraReports.UI.XRLabel lblDateColumnSoldItems;
        private DevExpress.XtraReports.UI.XRLabel lblItemDescriptionColumnSoldItems;
        private DevExpress.XtraReports.UI.XRLabel lblCodeColumnSoldItems;
        private DevExpress.XtraReports.UI.XRLabel lblRoomColumnSoldItems;
    }
}
